module HttpStatusCodes
  
  HTTP_OK_CODE = 200

  HTTP_BAD_REQUEST_CODE = 400
  HTTP_UNAUTHORIZED_CODE = 401
  HTTP_FORBIDDEN_CODE = 403
  HTTP_NOT_FOUND_CODE = 404
  HTTP_UNPROCESSABLE_ENTITY_CODE = 422
  HTTP_TOO_MANY_REQUESTS = 429
  HTTP_SERVER_ERROR = 500
  HTTP_GATEWAY_TIMEOUT = 504

end