version: "3.8"

services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: at_lunchtime_discovery_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgresdb:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  app: &app_base
    build:
      context: .
    image: tez123z/at_lunchtime_discovery_api
    environment:
      - DB_HOST=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_SIDEKIQ_URL=redis://redis:6379/0
      - REDIS_CABLE_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/2
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_DOMAIN
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_AUTHENTICATION
      - SMTP_ENABLE_STARTTLS_AUTO
    ports:
      - 3000:3000
    links:
      - postgresql
      - redis

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    ports: []
    depends_on:
      - app

volumes:
  postgresdb:
